### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by eshoule** [Kyle01/Coinspace#1]
Below is your proposal feedback. Address all items that are not checked. Once you do this, I will look at your proposal again and close the issue. You will need to create a new issue for every MVP, and we will follow a similar process throughout the project. I will close issues as you complete them.

# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments:
* Add bullet points on your wiki page that are links to the other pages, like this (https://github.com/appacademy/bluebird/wiki)
---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [  ] Each MVP is broken down into bullet points
- [x] Ensure all features have this criteria (except heroku/README)
    - [x] Adequate styling
    - [x] Smooth, bug-free navigation
    - [x] Adequate and appropriate seeds to demonstrate the feature

## Comments:
* Emphasize CRUD in the feature that has it.
* Format your list like this (https://github.com/appacademy/bluebird/wiki/mvp-list) - add 'hosting on heroku' and 'production README' to your list. Put 'hosting on heroku' second (after user auth) so that you have something to host.
* You currently only have 3 MVPs (other than user auth, heroku, and README). You need another MVP. According to your original plan, it appears that a watchlist is the fourth. Add this.

---

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments:
* You need to add the following columns to your users table: session_token, created_at, updated_at
* Add created_at and updated_at columns to all tables
* Style based on this example (https://github.com/appacademy/bluebird/wiki/schema)- you forgot backticks and your column names and details (e.g. foreign_key) should be snake_case
* Your notes say a position will have one coin, but I don't see any coin_id column in your positions table
---

# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments:
* Format routes pages based on these examples (https://github.com/appacademy/bluebird/wiki/backend-routes, https://github.com/appacademy/bluebird/wiki/frontend-routes)
* You will likely need to add routes when you add an additional MVP.
---

# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema 
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
    
## Comments:
* Add a session slice of state.
* Ensure all keys are lower case and camelCase.

- [x] When you add the additional MVP (watchlist), add all necessary information to each page (routes, schema, sample state).

**Comment by Kyle01** [comment]
Hi Liz. Thanks for going through my proposal and meeting with me yesterday. I have done my best to update it based on your feedback. Please review and tell me if you find any discrepancies or have any questions. Thank you!

**Comment by eshoule** [comment]
I'm going to close this, but you still need to backtick your column names in your schema tables. Good job!
