### ISSUE TITLE
MVP 2. User authentication

### ISSUE THREAD

**Issue by Kyle01** [Kyle01/Coinspace#2]
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] Users can’t use certain features without logging in (like seeing a portfolio)
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by eshoule** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [ ] Can't sign up with the same username/email
* When I try to do this it brings me to a blank page - doesn't show error messages
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)


Awesome job! Fix the unchecked items, and I will close the issue.

**Comment by Kyle01** [comment]
Hi Liz. MVP 2 looks complete. Sorry for the delay. Please tell me if you have any follow up questions.
